[package]
name = "radbd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
byteorder = "1.4.3"
crossbeam-channel = "0.5.8"
libusb1-sys = "0.6.4"
static_assertions = "1.1.0"
